services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cantinacf-nginx
    restart: unless-stopped
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
      - ./nginx/data:/etc/nginx/conf.d
    environment:
      DOMAIN: ${DOMAIN}
    depends_on:
      - cantinacf-frontend
    networks:
      - cantinacf

  certbot:
    image: certbot/certbot:latest
    container_name: cantinacf-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  cantinacf-backend:
    build:
      context: ./backend
    container_name: cantinacf-backend
    hostname: cantinacf-backend
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    networks:
      - cantinacf
    environment:
      TZ: America/Maceio

  cantinacf-frontend:
    build:
      context: ./frontend
    container_name: cantinacf-frontend
    hostname: cantinacf-frontend
    command:
      - sh
      - -c
      - |
        npm install && \
        npm run build && \
        npm start
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://cantinacf-backend:5000
    networks:
      - cantinacf
    depends_on:
      - cantinacf-backend

networks:
  cantinacf:
    driver: bridge
    name: cantinacf-network

volumes:
  nginx_data:
    driver: local
