services:
  cantinacf-backend:
    build:
      context: ./backend
    container_name: cantinacf-backend
    hostname: cantinacf-backend
    volumes:
      - ./backend/cantina/static/uploads:/app/cantina/static/uploads
      - ./backend/cantina/instance:/app/cantina/instance
    environment:
      - TZ=${TIMEZONE}

  cantinacf-frontend:
    build:
      context: ./frontend
    container_name: cantinacf-frontend
    hostname: cantinacf-frontend
    command: npm start
    ports:
      - ${WEBUI_PORT}:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://cantinacf-backend:5000
    depends_on:
      - cantinacf-backend
