"""remove payroll table once its unused

Revision ID: 1a859e1b3916
Revises: a26313c1c0f6
Create Date: 2024-05-04 22:02:22.738859

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a859e1b3916"
down_revision = "a26313c1c0f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payroll")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("value", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("affiliation_id", sa.INTEGER(), nullable=True),
        sa.Column("added_at", sa.DATETIME(), nullable=True),
        sa.Column("allowed_by", sa.INTEGER(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["affiliation_id"],
            ["affiliation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["allowed_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
