"""add is_deleted mixin

Revision ID: 28819ca43a57
Revises: d8ca4751db15
Create Date: 2024-08-04 20:37:35.561721

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28819ca43a57"
down_revision = "d8ca4751db15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("0")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
