"""Git pull

Revision ID: 3ab3a08ab96e
Revises: 40f51b528dc0
Create Date: 2023-08-05 22:59:14.327361

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ab3a08ab96e"
down_revision = "40f51b528dc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edit_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("route_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("category_page_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("page_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_edit_history_category_page",
            "category_page",
            ["category_page_id"],
            ["id"],
        )
        batch_op.create_foreign_key("fk_edit_history_page", "page", ["page_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_edit_history_route", "route", ["route_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("edit_history", schema=None) as batch_op:
        batch_op.drop_constraint("fk_edit_history_page", type_="foreignkey")
        batch_op.drop_constraint("fk_edit_history_route", type_="foreignkey")
        batch_op.drop_constraint("fk_edit_history_category_page", type_="foreignkey")
        batch_op.drop_column("page_id")
        batch_op.drop_column("category_page_id")
        batch_op.drop_column("route_id")

    # ### end Alembic commands ###
