"""Add transaction_data to Payment

Revision ID: 590a4210fa45
Revises: 28819ca43a57
Create Date: 2024-08-15 22:00:48.549605

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "590a4210fa45"
down_revision = "28819ca43a57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("transaction_data", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment", schema=None) as batch_op:
        batch_op.drop_column("transaction_data")

    # ### end Alembic commands ###
