"""remove unused product columns

Revision ID: 8990a899a697
Revises: 6a8afa99938d
Create Date: 2024-04-28 13:45:40.736430

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8990a899a697"
down_revision = "6a8afa99938d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("edit_history", schema=None) as batch_op:
        batch_op.drop_constraint("fk_edit_history_category_page", type_="foreignkey")
        batch_op.drop_constraint("fk_edit_history_page", type_="foreignkey")
        batch_op.drop_constraint("fk_edit_history_route", type_="foreignkey")
        batch_op.drop_column("page_id")
        batch_op.drop_column("route_id")
        batch_op.drop_column("category_page_id")

    op.drop_table("page")
    op.drop_table("category_page")
    op.drop_table("route")

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("type")
        batch_op.drop_column("description")

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_column("allowed_routes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.add_column(sa.Column("allowed_routes", sa.TEXT(), nullable=True))

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("type", sa.TEXT(), nullable=False))

    with op.batch_alter_table("edit_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_page_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("route_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("page_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_edit_history_route", "route", ["route_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_edit_history_page", "page", ["page_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_edit_history_category_page",
            "category_page",
            ["category_page_id"],
            ["id"],
        )

    op.create_table(
        "route",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("endpoint", sa.TEXT(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("block_recurring_access", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "category_page",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "page",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("route_id", sa.INTEGER(), nullable=False),
        sa.Column("category_page_id", sa.INTEGER(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("appear_navbar", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_page_id"],
            ["category_page.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("cart")
    # ### end Alembic commands ###
