"""remove unused tables

Revision ID: d8ca4751db15
Revises: 1a859e1b3916
Create Date: 2024-06-06 13:36:55.623097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ca4751db15'
down_revision = '1a859e1b3916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_history')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.Column('target_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('finished_by_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['finished_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('observations', sa.TEXT(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('received_by', sa.INTEGER(), nullable=True),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sale_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
